name: update-data
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
jobs:
  update-data:
    name: "Update Data"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Update Data
        run: |
          yarn install
          for _ in 1 2; do yarn update-data && break; done
        env:
          SHEETON_API_KEY: ${{ secrets.SHEETON_API_KEY }}
        working-directory: updater/
      - name: Commit
        uses: EndBug/add-and-commit@v6
        with:
          message: "Update Data"
          push: true
      - name: SpreadSheet URL
        if: failure()
        run: echo "Go to https://docs.google.com/spreadsheets/d/1y1pqQhBIV_uGCp-AzxSQwLDOV4v_tIPobnQJmFMJVDc/edit#gid=0"
