name: update-data
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-data:
    name: "Update Data"
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Update Data
        run: yarn install && yarn update-data
        env:
          SHEETON_API_KEY: ${{ secrets.SHEETON_API_KEY }}
        working-directory: updater/
      - name: Commit
        uses: EndBug/add-and-commit@v6
        with:
          message: "Update Data"
          push: true
