name: update-data
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
jobs:
  update-data:
    name: "Update Data"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node.js
        uses: actions/setup-node@v
        with:
          node-version: 18
          cache: 'yarn'
      - name: Update Data
        run: |
          yarn install
          for _ in 1 2 3; do yarn run update-data && break; done
        env:
          SHEETON_API_KEY: ${{ secrets.SHEETON_API_KEY }}
        working-directory: updater/
      - name: Commit
        uses: EndBug/add-and-commit@v9
        if: success()
        with:
          message: "Update Data"
          push: true
      - name: SpreadSheet URL
        if: failure()
        run: |
          # if exists GITHUB_SUMMARY.md, append to GITHUB_STEP_SUMMARY
          [ -f GITHUB_SUMMARY.md ] && cat GITHUB_SUMMARY.md >> $GITHUB_STEP_SUMMARY
          echo "## SpreadSheet URL" >> $GITHUB_STEP_SUMMARY
          echo "Go to https://docs.google.com/spreadsheets/d/1y1pqQhBIV_uGCp-AzxSQwLDOV4v_tIPobnQJmFMJVDc/edit#gid=0" >> $GITHUB_STEP_SUMMARY
